In [1]:
from google.colab import drive
drive.mount('/content/drive') 

Mounted at /content/drive


In [2]:
cd /content/drive/MyDrive/MCC/Thesis/Notebooks/DecisionTree

/content/drive/MyDrive/MCC/Thesis/Notebooks/DecisionTree


In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("./atus_anual_2019.csv", index_col=False)

In [4]:
df.head()

COBERTURA  ID_ENTIDAD  ...     CLASACC             ESTATUS
0  Municipal           1  ...    No fatal  Cifras Definitivas
1  Municipal           1  ...    No fatal  Cifras Definitivas
2  Municipal           1  ...  S�lo da�os  Cifras Definitivas
3  Municipal           1  ...  S�lo da�os  Cifras Definitivas
4  Municipal           1  ...  S�lo da�os  Cifras Definitivas

[5 rows x 45 columns]

In [5]:
df.shape

(378671, 45)

In [6]:
for col in df:
  print(col)

COBERTURA
ID_ENTIDAD
ID_MUNICIPIO
ANIO
MES
ID_HORA
ID_MINUTO
ID_DIA
DIASEMANA
URBANA
SUBURBANA
TIPACCID
AUTOMOVIL
CAMPASAJ
MICROBUS
PASCAMION
OMNIBUS
TRANVIA
CAMIONETA
CAMION
TRACTOR
FERROCARRI
MOTOCICLET
BICICLETA
OTROVEHIC
CAUSAACCI
CAPAROD
SEXO
ALIENTO
CINTURON
ID_EDAD
CONDMUERTO
CONDHERIDO
PASAMUERTO
PASAHERIDO
PEATMUERTO
PEATHERIDO
CICLMUERTO
CICLHERIDO
OTROMUERTO
OTROHERIDO
NEMUERTO
NEHERIDO
CLASACC
ESTATUS


In [12]:
for col in df:
  print(df[col].describe())
  print("---------------------------------")

count        378671
unique            1
top       Municipal
freq         378671
Name: COBERTURA, dtype: object
---------------------------------
count    378671.000000
mean         16.655569
std           7.735531
min           1.000000
25%          11.000000
50%          19.000000
75%          22.000000
max          32.000000
Name: ID_ENTIDAD, dtype: float64
---------------------------------
count    378671.000000
mean         41.665998
std          56.607910
min           1.000000
25%          14.000000
50%          30.000000
75%          46.000000
max         570.000000
Name: ID_MUNICIPIO, dtype: float64
---------------------------------
count    378671.0
mean       2019.0
std           0.0
min        2019.0
25%        2019.0
50%        2019.0
75%        2019.0
max        2019.0
Name: ANIO, dtype: float64
---------------------------------
count    378671.000000
mean          6.601884
std           3.467628
min           1.000000
25%           4.000000
50%           7.000000
75%     

In [13]:
for col in df:
  print(col)
  print(len(df[col].unique()))
  print(df[col].unique())
  print()

COBERTURA
1
['Municipal']

ID_ENTIDAD
32
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32]

ID_MUNICIPIO
570
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119  95 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 20

In [ ]:
df["REGION"] = df["ID_ENTIDAD"].astype(str) + "-" + df["ID_MUNICIPIO"].astype(str)
df = df.drop(columns=['COBERTURA', 'ID_MINUTO', 'ID_DIA', 'ESTATUS', 'ID_ENTIDAD', 'ID_MUNICIPIO', 'MICROBUS', 'OMNIBUS', 'TRANVIA', 'TRACTOR', 'FERROCARRI', 'CONDMUERTO', 'PASAMUERTO', 'PEATMUERTO', 'CICLMUERTO', 'OTROMUERTO', 'PEATHERIDO', 'CICLHERIDO', 'OTROHERIDO', 'NEMUERTO', 'NEHERIDO', 'URBANA', 'SUBURBANA', 'CAMPASAJ', 'PASCAMION', 'CAMIONETA', 'CAMION', 'MOTOCICLET', 'BICICLETA', 'OTROVEHIC', 'CAPAROD', 'PASAHERIDO'])
df["DIASEMANA"] = df['DIASEMANA'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["TIPACCID"] = df['TIPACCID'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["CAUSAACCI"] = df['CAUSAACCI'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["SEXO"] = df['SEXO'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["ALIENTO"] = df['ALIENTO'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["CINTURON"] = df['CINTURON'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["CLASACC"] = df['CLASACC'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["TIPACCID"].replace({"colision con vehculo automotor": "colision con vehiculo automotor", "cada de pasajero": "caida de pasajero", "colisin con animal": "colision con animal", "colisin con ciclista": "colision con ciclista", "colisin con ferrocarril": "colision con ferrocarril", "colisin con motocicleta": "colision con motocicleta", "colisin con objeto fijo": "colision con objeto fijo", "colisin con peatn (atropellamiento)": "colision con peaton (atropellamiento)", "colisin con vehculo automotor": "colision con vehculo automotor"}, inplace=True)
df["SEXO"].replace({"se fug": "se fugo"}, inplace=True)
df["ALIENTO"].replace({"s": "si"}, inplace=True)
df["CINTURON"].replace({"s": "si"}, inplace=True)
df["CAUSAACCI"].replace({"falla del vehculo": "falla del vehiculo", "mala condicin del camino": "mala condicion del camino", "peatn o pasajero": "peaton o pasajero"}, inplace=True)
df["CLASACC"].replace({"slo daos": "solo danos"}, inplace=True)
df = df[df.SEXO != "Certificado cero"]
df = df.drop(df[(df.DIASEMANA == 'certificado cero')].index)
df.head()

ANIO  MES  ID_HORA DIASEMANA  ... ID_EDAD  CONDHERIDO     CLASACC REGION
0  2009    1        1    sabado  ...      18           0  solo danos    1-1
1  2009    1       11    sabado  ...      39           0  solo danos    1-1
2  2009    1       17    sabado  ...      44           0  solo danos    1-1
3  2009    1       18    sabado  ...      51           1    no fatal    1-1
4  2009    1       19    sabado  ...      37           0  solo danos    1-1

[5 rows x 14 columns]

In [ ]:
for col in df:
  print(col)
  print(len(df[col].unique()))
  print(df[col].unique())
  print()

ANIO
11
[2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019]

MES
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]

ID_HORA
25
[ 1 11 17 18 19 21  0  3  8 10 15 16 22 23  2  4 12  7  9 13 14 20  6  5
 99]

DIASEMANA
8
['sabado' 'viernes' 'domingo' 'lunes' 'martes' 'miercoles' 'jueves'
 'no especificado']

TIPACCID
14
['colision con objeto fijo' 'colision con vehiculo automotor'
 'colision con motocicleta' 'colision con ciclista' 'salida del camino'
 'volcadura' 'colision con peaton (atropellamiento)' 'caida de pasajero'
 'colision con animal' 'otro' 'colision con ferrocarril' 'incendio'
 'certificado cero' 'colision con vehculo automotor']

AUTOMOVIL
10
[1 0 2 3 4 6 5 7 9 8]

CAUSAACCI
6
['conductor' 'falla del vehiculo' 'peaton o pasajero' 'otra'
 'mala condicion del camino' 'certificado cero']

SEXO
4
['hombre' 'se fugo' 'mujer' 'certificado cero']

ALIENTO
4
['si' 'no' 'se ignora' 'certificado cero']

CINTURON
4
['se ignora' 'no' 'si' 'certificado cero']

ID_EDAD
89
[18 39 44 51 37 35 2

In [ ]:
df.to_csv('atus_2009_2019.csv',index=False)