In [5]:
from google.colab import drive
drive.mount('/content/drive') 

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
cd /content/drive/MyDrive/MCC/Thesis/Notebooks/DecisionTree

/content/drive/MyDrive/MCC/Thesis/Notebooks/DecisionTree


In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import plot_confusion_matrix

%matplotlib inline

df = pd.read_csv("./atus_2009_2019.csv", index_col=False)

In [12]:
for col in df:
  print(col)
  print(len(df[col].unique()))
  print(df[col].unique())
  print()

ANIO
11
[2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019]

MES
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]

ID_HORA
25
[ 1 11 17 18 19 21  0  3  8 10 15 16 22 23  2  4 12  7  9 13 14 20  6  5
 99]

DIASEMANA
9
['sabado' 'viernes' 'domingo' 'lunes' 'martes' 'miercoles' 'jueves'
 'no especificado' 'certificado cero']

TIPACCID
14
['colision con objeto fijo' 'colision con vehiculo automotor'
 'colision con motocicleta' 'colision con ciclista' 'salida del camino'
 'volcadura' 'colision con peaton (atropellamiento)' 'caida de pasajero'
 'colision con animal' 'otro' 'colision con ferrocarril' 'incendio'
 'certificado cero' 'colision con vehculo automotor']

AUTOMOVIL
10
[1 0 2 3 4 6 5 7 9 8]

CAUSAACCI
6
['conductor' 'falla del vehiculo' 'peaton o pasajero' 'otra'
 'mala condicion del camino' 'certificado cero']

SEXO
4
['hombre' 'se fugo' 'mujer' 'certificado cero']

ALIENTO
4
['si' 'no' 'se ignora' 'certificado cero']

CINTURON
4
['se ignora' 'no' 'si' 'certificado cero']

ID_EDAD
89
[

In [13]:
df = df.drop(columns=['MES', 'ANIO'])

df = df[df.DIASEMANA != "certificado cero"]
df = df[df.TIPACCID != "certificado cero"]
df = df[df.ID_HORA != 99]

df.REGION = pd.factorize(df.REGION)[0]

df.DIASEMANA = pd.factorize(df.DIASEMANA)[0]

df.TIPACCID = pd.factorize(df.TIPACCID)[0]

df.CAUSAACCI = pd.factorize(df.CAUSAACCI)[0]

df.SEXO = pd.factorize(df.SEXO)[0]

df.ALIENTO = pd.factorize(df.ALIENTO)[0]

df.CINTURON = pd.factorize(df.CINTURON)[0]

df.CLASACC = pd.factorize(df.CLASACC)[0]

In [14]:
for col in df:
  print(col)
  print(len(df[col].unique()))
  print(df[col].unique())
  print()

ID_HORA
24
[ 1 11 17 18 19 21  0  3  8 10 15 16 22 23  2  4 12  7  9 13 14 20  6  5]

DIASEMANA
8
[0 1 2 3 4 5 6 7]

TIPACCID
13
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]

AUTOMOVIL
10
[1 0 2 3 4 6 5 7 9 8]

CAUSAACCI
5
[0 1 2 3 4]

SEXO
3
[0 1 2]

ALIENTO
3
[0 1 2]

CINTURON
3
[0 1 2]

ID_EDAD
89
[18 39 44 51 37 35 23 32 22 21 24 28 26 33 43 72  0 19 20 56 57 48 53 50
 31 52 76 34 25 46 27 49 17 64 67 45 61 36 55 41 38 42 30 71 47 58 59 80
 40 14 70 29 65 99 54 63 15 16 62 69 60 68 12 74 82 73 66 86 13 85 77 79
 75 78 84 83 90 81 88 87 92 89 93 91 95 94 97 98 96]

CONDHERIDO
10
[0 1 2 5 3 4 8 7 6 9]

CLASACC
3
[0 1 2]

REGION
2024
[   0    1    2 ... 2021 2022 2023]



In [15]:
df.to_csv('atus_2009_2019_clean.csv',index=False)