In [ ]:
from google.colab import drive
drive.mount('/content/drive') 

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/MyDrive/MCC/Thesis/Notebooks/DecisionTree

/content/drive/MyDrive/MCC/Thesis/Notebooks/DecisionTree


In [ ]:
import pandas as pd
import numpy as np
acc1 = pd.read_csv("./atus_anual_2009.csv", index_col=False)
acc2 = pd.read_csv("./atus_anual_2010.csv", index_col=False)
acc3 = pd.read_csv("./atus_anual_2011.csv", index_col=False)
acc4 = pd.read_csv("./atus_anual_2012.csv", index_col=False)
acc5 = pd.read_csv("./atus_anual_2013.csv", index_col=False)
acc6 = pd.read_csv("./atus_anual_2014.csv", index_col=False)
acc7 = pd.read_csv("./atus_anual_2015.csv", index_col=False)
acc8 = pd.read_csv("./atus_anual_2016.csv", index_col=False)
acc9 = pd.read_csv("./atus_anual_2017.csv", index_col=False)
acc10 = pd.read_csv("./atus_anual_2018.csv", index_col=False)
acc11 = pd.read_csv("./atus_anual_2019.csv", index_col=False)

In [ ]:
df = acc1.append(acc2, ignore_index = True)
df = df.append(acc3, ignore_index = True)
df = df.append(acc4, ignore_index = True)
df = df.append(acc5, ignore_index = True)
df = df.append(acc6, ignore_index = True)
df = df.append(acc7, ignore_index = True)
df = df.append(acc8, ignore_index = True)
df = df.append(acc9, ignore_index = True)
df = df.append(acc10, ignore_index = True)
df = df.append(acc11, ignore_index = True)

In [ ]:
df.head()

COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ...  NEHERIDO     CLASACC           ESTATUS
0  Municipal           1             1  ...         0  Sólo daños  Cifras Revisadas
1  Municipal           1             1  ...         0  Sólo daños  Cifras Revisadas
2  Municipal           1             1  ...         0  Sólo daños  Cifras Revisadas
3  Municipal           1             1  ...         0    No fatal  Cifras Revisadas
4  Municipal           1             1  ...         0  Sólo daños  Cifras Revisadas

[5 rows x 45 columns]

In [ ]:
df.shape

(4269960, 45)

In [ ]:
for col in df:
  print(col)

COBERTURA
ID_ENTIDAD
ID_MUNICIPIO
ANIO
MES
ID_HORA
ID_MINUTO
ID_DIA
DIASEMANA
URBANA
SUBURBANA
TIPACCID
AUTOMOVIL
CAMPASAJ
MICROBUS
PASCAMION
OMNIBUS
TRANVIA
CAMIONETA
CAMION
TRACTOR
FERROCARRI
MOTOCICLET
BICICLETA
OTROVEHIC
CAUSAACCI
CAPAROD
SEXO
ALIENTO
CINTURON
ID_EDAD
CONDMUERTO
CONDHERIDO
PASAMUERTO
PASAHERIDO
PEATMUERTO
PEATHERIDO
CICLMUERTO
CICLHERIDO
OTROMUERTO
OTROHERIDO
NEMUERTO
NEHERIDO
CLASACC
ESTATUS


In [ ]:
df["REGION"] = df["ID_ENTIDAD"].astype(str) + "-" + df["ID_MUNICIPIO"].astype(str)
df = df.drop(columns=['COBERTURA', 'ID_MINUTO', 'ID_DIA', 'ESTATUS', 'ID_ENTIDAD', 'ID_MUNICIPIO', 'MICROBUS', 'OMNIBUS', 'TRANVIA', 'TRACTOR', 'FERROCARRI', 'CONDMUERTO', 'PASAMUERTO', 'PEATMUERTO', 'CICLMUERTO', 'OTROMUERTO', 'PEATHERIDO', 'CICLHERIDO', 'OTROHERIDO', 'NEMUERTO', 'NEHERIDO', 'URBANA', 'SUBURBANA', 'CAMPASAJ', 'PASCAMION', 'CAMIONETA', 'CAMION', 'MOTOCICLET', 'BICICLETA', 'OTROVEHIC', 'CAPAROD', 'PASAHERIDO'])
df["DIASEMANA"] = df['DIASEMANA'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["TIPACCID"] = df['TIPACCID'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["CAUSAACCI"] = df['CAUSAACCI'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["SEXO"] = df['SEXO'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["ALIENTO"] = df['ALIENTO'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["CINTURON"] = df['CINTURON'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["CLASACC"] = df['CLASACC'].str.lower().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["TIPACCID"].replace({"colision con vehculo automotor": "colision con vehiculo automotor", "cada de pasajero": "caida de pasajero", "colisin con animal": "colision con animal", "colisin con ciclista": "colision con ciclista", "colisin con ferrocarril": "colision con ferrocarril", "colisin con motocicleta": "colision con motocicleta", "colisin con objeto fijo": "colision con objeto fijo", "colisin con peatn (atropellamiento)": "colision con peaton (atropellamiento)", "colisin con vehculo automotor": "colision con vehculo automotor"}, inplace=True)
df["SEXO"].replace({"se fug": "se fugo"}, inplace=True)
df["ALIENTO"].replace({"s": "si"}, inplace=True)
df["CINTURON"].replace({"s": "si"}, inplace=True)
df["CAUSAACCI"].replace({"falla del vehculo": "falla del vehiculo", "mala condicin del camino": "mala condicion del camino", "peatn o pasajero": "peaton o pasajero"}, inplace=True)
df["CLASACC"].replace({"slo daos": "solo danos"}, inplace=True)
df = df[df.SEXO != "Certificado cero"]
df = df.drop(df[(df.DIASEMANA == 'certificado cero')].index)
df.head()

ANIO  MES  ID_HORA DIASEMANA  ... ID_EDAD  CONDHERIDO     CLASACC REGION
0  2009    1        1    sabado  ...      18           0  solo danos    1-1
1  2009    1       11    sabado  ...      39           0  solo danos    1-1
2  2009    1       17    sabado  ...      44           0  solo danos    1-1
3  2009    1       18    sabado  ...      51           1    no fatal    1-1
4  2009    1       19    sabado  ...      37           0  solo danos    1-1

[5 rows x 14 columns]

In [ ]:
for col in df:
  print(col)
  print(len(df[col].unique()))
  print(df[col].unique())
  print()

ANIO
11
[2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019]

MES
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]

ID_HORA
25
[ 1 11 17 18 19 21  0  3  8 10 15 16 22 23  2  4 12  7  9 13 14 20  6  5
 99]

DIASEMANA
8
['sabado' 'viernes' 'domingo' 'lunes' 'martes' 'miercoles' 'jueves'
 'no especificado']

TIPACCID
14
['colision con objeto fijo' 'colision con vehiculo automotor'
 'colision con motocicleta' 'colision con ciclista' 'salida del camino'
 'volcadura' 'colision con peaton (atropellamiento)' 'caida de pasajero'
 'colision con animal' 'otro' 'colision con ferrocarril' 'incendio'
 'certificado cero' 'colision con vehculo automotor']

AUTOMOVIL
10
[1 0 2 3 4 6 5 7 9 8]

CAUSAACCI
6
['conductor' 'falla del vehiculo' 'peaton o pasajero' 'otra'
 'mala condicion del camino' 'certificado cero']

SEXO
4
['hombre' 'se fugo' 'mujer' 'certificado cero']

ALIENTO
4
['si' 'no' 'se ignora' 'certificado cero']

CINTURON
4
['se ignora' 'no' 'si' 'certificado cero']

ID_EDAD
89
[18 39 44 51 37 35 2

In [ ]:
df.to_csv('atus_2009_2019.csv',index=False)